# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "fman"
version = "1.0.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "fpm plug-in application that displays Fortran intrinsics documentation"

[dependencies]

[dependencies.M_CLI2]
   git = "https://github.com/urbanjost/M_CLI2.git"

[dependencies.M_escape]
   git = "https://github.com/urbanjost/M_escape.git"

[dependencies.M_match]
   git = "https://github.com/urbanjost/M_match.git"

[dependencies.M_strings]
   git = "https://github.com/urbanjost/M_strings.git"

[[executable]]
name = "fman"
source-dir = "app/"
main="fman.f90"
